openapi: 3.0.1
info:
  title: Documentación del módulo Users
  version: 1.0.0
  description: API para gestión de usuarios en la app de mascotas

paths:
  /api/users:
    get:
      summary: Obtiene todos los usuarios almacenados en la base de datos
      tags:
        - Users
      responses:
        "200":
          description: Lista de usuarios obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        "500":
          description: Error interno del servidor
          
  /api/users/getusers:
    get:
      summary: Obtiene todos los usuarios
      tags:
        - Users
      responses:
        "200":
          description: Lista de usuarios obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        "500":
          description: Error interno del servidor

  /api/users/mockingusers:
    get:
      summary: Crea usuarios de prueba (mock)
      tags:
        - Users
      responses:
        "200":
          description: Usuarios de prueba creados correctamente
        "500":
          description: Error interno del servidor

  /api/users/mockingpets:
    get:
      summary: Crea mascotas de prueba (mock)
      tags:
        - Users
      responses:
        "200":
          description: Mascotas de prueba creadas correctamente
        "500":
          description: Error interno del servidor

  /api/users/generateData:
    post:
      summary: Genera datos de prueba
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usersCount:
                  type: integer
                  description: Número de usuarios a generar
                petsCount:
                  type: integer
                  description: Número de mascotas a generar
              example:
                usersCount: 10
                petsCount: 20
      responses:
        "201":
          description: Datos generados exitosamente
        "500":
          description: Error interno del servidor

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          description: ID autogenerado por MongoDB
        first_name:
          type: string
          description: Nombre del usuario
        last_name:
          type: string
          description: Apellido del usuario
        email:
          type: string
          description: Correo electrónico del usuario
        password:
          type: string
          description: Contraseña del usuario
        role:
          type: string
          description: "Rol del usuario (por defecto: user)"
        pets:
          type: array
          description: Lista de mascotas asociadas al usuario
          items:
            type: object
            properties:
              _id:
                type: string
                description: ID de la mascota
      example:
        _id: "647f6b2a12a4f3f1c8a8e9b1"
        first_name: Juan
        last_name: Pérez
        email: juan.perez@example.com
        password: "hashedpassword123"
        role: user
        pets:
          - _id: "647f6b2a12a4f3f1c8a8e9c2"
          - _id: "647f6b2a12a4f3f1c8a8e9c3"
